[versions]
agp = "8.8.1" # Android Gradle Plugin (совместим с Kotlin 2.0.21)
glide = "4.16.0"
kotlin = "2.0.21"
coreKtx = "1.13.0"
appcompat = "1.6.1"
kotlinxCoroutinesAndroid = "1.10.1"
kotlinxSerializationJsonVersion = "1.6.3"
material = "1.11.0"
activity = "1.9.0"
constraintlayout = "2.2.0-alpha13" # Актуальная версия
navigationCompose = "2.7.7" # Совместима с Kotlin 2.0.21
okhttp = "4.12.0" # Чистая Java-библиотека (не требует Kotlin)
retrofit = "2.11.0"
kotlinxSerializationJson = "1.7.0"
recyclerview = "1.3.2"
room= "2.7.2"

# Тестовые зависимости
junit = "4.13.2"
androidxJunit = "1.1.5"
espressoCore = "3.5.1"
retrofit2KotlinxSerializationConverter = "1.0.0"
firebaseCrashlyticsBuildtools = "3.0.6"

[libraries]
# AndroidX

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-serialization-json-v163 = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJsonVersion" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# Navigation
androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationCompose" }
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationCompose" }

# Сетевая работа
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
okhttp3-okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

# Kotlin
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

# Тестирование
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJunit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
retrofit2-kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2KotlinxSerializationConverter" }
firebase-crashlytics-buildtools = { group = "com.google.firebase", name = "firebase-crashlytics-buildtools", version.ref = "firebaseCrashlyticsBuildtools" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }